<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<InvariantGlobalization>true</InvariantGlobalization>
	</PropertyGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="SpellCrafter.Tests" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\SpellCrafter\SpellCrafter.csproj" />
	</ItemGroup>
</Project>
