<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<TrimMode>copyused</TrimMode>
		<BuiltInComInteropSupport>true</BuiltInComInteropSupport>
		<!--Publish AOT-->
		<PublishAot>true</PublishAot>
		<OptimizationPreference>Speed</OptimizationPreference>
		<InvariantGlobalization>true</InvariantGlobalization>
		<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
		<StripSymbols>true</StripSymbols>
	</PropertyGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="SpellCrafter.Tests" />
	</ItemGroup>
	<PropertyGroup Condition="'$(OS)' == 'Windows_NT'">
		<DefineConstants>$(DefineConstants);WINDOWS</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(OS)' != 'Windows_NT'">
		<DefineConstants>$(DefineConstants);LINUX</DefineConstants>
	</PropertyGroup>
	
	<ItemGroup>
		<Content Include=".ReflectionDefine\**" />
		<AvaloniaResource Include="Assets\**" />
		<AvaloniaResource Remove="Assets\Icons.axaml" />
		<None Remove=".gitignore" />
	</ItemGroup>
	
	<!--AOT Reflection Define-->

	<ItemGroup>
		<!--This helps with theme dll-s trimming.
        If you will publish your application in self-contained mode with p:PublishTrimmed=true and it will use Fluent theme Default theme will be trimmed from the output and vice versa.
        https://github.com/AvaloniaUI/Avalonia/issues/5593 -->
		<TrimmableAssembly Include="Material.Avalonia" />
		<TrimmableAssembly Include="Avalonia.Themes.Default" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AngleSharp" Version="1.1.2" />
		<PackageReference Include="Avalonia" Version="11.1.3" />
		<PackageReference Include="Avalonia.Controls.DataGrid" Version="11.1.3" />
		<PackageReference Include="Avalonia.Desktop" Version="11.1.3" />
		<!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
		<PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.1.3" />
		<PackageReference Include="Avalonia.ReactiveUI" Version="11.1.3" />
		<PackageReference Include="Fody" Version="6.8.2">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Material.Avalonia" Version="3.7.4" />
		<PackageReference Include="Material.Avalonia.DataGrid" Version="3.7.4" />
		<PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.11.0" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.11.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="PublishAotCompressed" Version="1.0.3" />
		<PackageReference Include="ReactiveUI.Fody" Version="19.5.41" />
		<PackageReference Include="SharpCompress" Version="0.38.0" />
		<PackageReference Include="sqlite-net-pcl" Version="1.9.172" />
		<PackageReference Include="SQLiteNetExtensions" Version="2.1.0" />
		<PackageReference Include="System.Data.SQLite" Version="1.0.119" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Controls\MenuButton.axaml.cs">
		  <DependentUpon>MenuButton.axaml</DependentUpon>
		</Compile>
		<Compile Update="Views\MainWindowView.axaml.cs">
		  <DependentUpon>MainWindowView.axaml</DependentUpon>
		</Compile>
		<Compile Update="Views\AddonDetailsView.axaml.cs">
			<DependentUpon>AddonDetailsView.axaml</DependentUpon>
		</Compile>
		<Compile Update="Views\AddonsOverviewView.axaml.cs">
		  <DependentUpon>AddonsOverviewView.axaml</DependentUpon>
		</Compile>
		<Compile Update="Views\BrowseView.axaml.cs">
		  <DependentUpon>BrowseView.axaml</DependentUpon>
		</Compile>
		<Compile Update="Views\InstalledAddonsView.axaml.cs">
		  <DependentUpon>InstalledAddonsView.axaml</DependentUpon>
		</Compile>
		<Compile Update="Views\SettingsView.axaml.cs">
		  <DependentUpon>SettingsView.axaml</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
	  <AvaloniaXaml Update="Assets\Icons.axaml">
	    <SubType>Designer</SubType>
	  </AvaloniaXaml>
	</ItemGroup>
</Project>
